using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Srclib.Nuget
{

    ///<summary>

    ///Nuget cannot load a package only if both
    ///name and version are provided, while visual studio configuration files
    ///hold only dependency name. So this class holds a name->version map for top several 
    ///hundred most popular nuget packages
    ///Generated based on https://www.nuget.org/stats/packageversions 

    ///</summary>
    public class PackageVersions
    {
        private Dictionary<string, string> versions;

        public PackageVersions()
        {
            versions = new Dictionary<string, string>()
            {
                { "microsoft.web.infrastructure", "1.0.0" },
                { "entityframework", "6.1.3" },
                { "newtonsoft.json", "8.0.2" },
                { "microsoft.aspnet.webapi.client", "5.2.3" },
                { "microsoft.aspnet.webpages", "3.2.3" },
                { "microsoft.aspnet.mvc", "5.2.3" },
                { "microsoft.aspnet.razor", "3.2.3" },
                { "owin", "1.0.0" },
                { "microsoft.aspnet.webapi.core", "5.2.3" },
                { "microsoft.aspnet.web.optimization", "1.1.3" },
                { "microsoft.aspnet.webapi.webhost", "5.2.3" },
                { "microsoft.owin", "3.0.1" },
                { "microsoft.aspnet.webapi", "5.2.3" },
                { "system.collections", "4.0.10" },
                { "system.resources.resourcemanager", "4.0.0" },
                { "system.runtime", "4.0.20" },
                { "microsoft.owin.host.systemweb", "3.0.1" },
                { "antlr", "3.4.1.9004" },
                { "microsoft.owin.security", "3.0.1" },
                { "system.threading", "4.0.10" },
                { "system.reflection.primitives", "4.0.0" },
                { "system.threading.tasks", "4.0.10" },
                { "system.io", "4.0.10" },
                { "system.private.uri", "4.0.0" },
                { "webgrease", "1.5.2" },
                { "system.reflection.extensions", "4.0.0" },
                { "system.text.encoding", "4.0.10" },
                { "system.io.filesystem.primitives", "4.0.0" },
                { "system.reflection", "4.0.0" },
                { "system.text.encoding.extensions", "4.0.10" },
                { "system.globalization", "4.0.0" },
                { "system.diagnostics.tracing", "4.0.20" },
                { "system.diagnostics.debug", "4.0.0" },
                { "system.runtime.extensions", "4.0.10" },
                { "system.io.filesystem", "4.0.0" },
                { "modernizr", "2.6.2" },
                { "system.runtime.handles", "4.0.0" },
                { "microsoft.bcl", "1.1.10" },
                { "system.linq.expressions", "4.0.10" },
                { "microsoft.owin.security.oauth", "3.0.1" },
                { "system.runtime.interopservices", "4.0.20" },
                { "system.threading.overlapped", "4.0.0" },
                { "microsoft.net.http", "2.2.29" },
                { "jquery", "1.10.2" },
                { "system.reflection.typeextensions", "4.0.0" },
                { "system.globalization.calendars", "4.0.0" },
                { "microsoft.aspnet.identity.core", "2.2.1" },
                { "microsoft.owin.security.cookies", "3.0.1" },
                { "system.objectmodel", "4.0.10" },
                { "microsoft.bcl.build", "1.0.21" },
                { "system.reflection.emit.ilgeneration", "4.0.0" },
                { "system.reflection.emit", "4.0.0" },
                { "microsoft.jquery.unobtrusive.validation", "3.2.3" },
                { "system.linq", "4.0.0" },
                { "microsoft.win32.primitives", "4.0.0" },
                { "system.reflection.emit.lightweight", "4.0.0" },
                { "bootstrap", "3.0.0" },
                { "system.collections.nongeneric", "4.0.0" },
                { "microsoft.aspnet.identity.owin", "2.2.1" },
                { "respond", "1.2.0" },
                { "system.runtime.numerics", "4.0.0" },
                { "moq", "4.2.1510.2205" },
                { "jquery.validation", "1.11.1" },
                { "microsoft.net.compilers", "1.0.0" },
                { "xunit.abstractions", "2.0.0" },
                { "system.collections.immutable", "1.1.37" },
                { "system.diagnostics.tools", "4.0.0" },
                { "system.text.regularexpressions", "4.0.10" },
                { "commonservicelocator", "1.3.0" },
                { "microsoft.bcl.async", "1.0.168" },
                { "microsoft.aspnet.identity.entityframework", "2.2.1" },
                { "nunit", "2.6.4" },
                { "xunit.extensibility.execution", "2.1.0" },
                { "system.security.principal", "4.0.0" },
                { "xunit.core", "2.1.0" },
                { "microsoft.aspnet.webapi.owin", "5.2.3" },
                { "xunit.extensibility.core", "2.1.0" },
                { "microsoft.codedom.providers.dotnetcompilerplatform", "1.0.0" },
                { "microsoft.azure.keyvault.core", "1.0.0" },
                { "microsoft.data.odata", "5.6.4" },
                { "system.collections.concurrent", "4.0.10" },
                { "microsoft.data.edm", "5.6.4" },
                { "system.spatial", "5.6.4" },
                { "system.componentmodel.primitives", "4.0.0" },
                { "xunit.assert", "2.1.0" },
                { "xunit", "2.1.0" },
                { "system.componentmodel", "4.0.0" },
                { "system.xml.readerwriter", "4.0.10" },
                { "log4net", "2.0.5" },
                { "system.security.claims", "4.0.0" },
                { "microsoft.aspnet.cors", "5.2.3" },
                { "microsoft.data.services.client", "5.6.4" },
                { "system.net.primitives", "4.0.10" },
                { "microsoft.owin.security.google", "3.0.1" },
                { "microsoft.owin.security.facebook", "3.0.1" },
                { "microsoft.applicationinsights", "1.2.3" },
                { "system.net.http", "4.0.0" },
                { "microsoft.owin.security.twitter", "3.0.1" },
                { "microsoft.owin.security.microsoftaccount", "3.0.1" },
                { "system.appcontext", "4.0.0" },
                { "system.private.networking", "4.0.0" },
                { "microsoft.applicationinsights.windowsserver.telemetrychannel", "1.2.3" },
                { "microsoft.applicationinsights.dependencycollector", "1.2.3" },
                { "microsoft.applicationinsights.perfcountercollector", "1.2.3" },
                { "microsoft.applicationinsights.windowsserver", "1.2.3" },
                { "microsoft.applicationinsights.web", "1.2.3" },
                { "autofac", "3.5.2" },
                { "system.componentmodel.eventbasedasync", "4.0.10" },
                { "microsoft.aspnet.webapi.cors", "5.2.3" },
                { "system.globalization.extensions", "4.0.0" },
                { "system.threading.timer", "4.0.0" },
                { "system.io.compression", "4.0.0" },
                { "windowsazure.storage", "6.2.0" },
                { "htmlagilitypack", "1.4.9" },
                { "microsoft.windowsazure.configurationmanager", "3.1.0" },
                { "nuget.commandline", "3.3.0" },
                { "system.reflection.metadata", "1.1.0" },
                { "microsoft.applicationinsights.agent.intercept", "1.2.0" },
                { "system.data.common", "4.0.0" },
                { "microsoft.aspnet.webapi.helppage", "5.2.3" },
                { "sharpziplib", "0.86.0" },
                { "restsharp", "105.2.3" },
                { "system.identitymodel.tokens.jwt", "4.0.2.206221351" },
                { "system.threading.threadpool", "4.0.10-beta-23409" },
                { "microsoft.aspnet.signalr.core", "2.2.0" },
                { "system.security.cryptography.primitives", "4.0.0-beta-23409" },
                { "system.threading.thread", "4.0.0-beta-23409" },
                { "system.xml.xmldocument", "4.0.0" },
                { "unity", "4.0.1" },
                { "system.threading.tasks.parallel", "4.0.0" },
                { "system.diagnostics.tracesource", "4.0.0-beta-23409" },
                { "system.collections.specialized", "4.0.0" },
                { "system.io.compression.clrcompression-x64", "4.0.0" },
                { "system.linq.queryable", "4.0.0" },
                { "system.io.compression.clrcompression-x86", "4.0.0" },
                { "microsoft.csharp", "4.0.0" },
                { "jquery.ui.combined", "1.11.4" },
                { "system.console", "4.0.0-beta-23409" },
                { "xunit.runner.utility", "2.1.0" },
                { "system.dynamic.runtime", "4.0.10" },
                { "microsoft.applicationinsights.javascript", "0.15.0-build58334" },
                { "microsoft.extensions.dependencyinjection.abstractions", "1.0.0-rc1-final" },
                { "nlog", "4.2.3" },
                { "microsoft.aspnet.signalr.js", "2.2.0" },
                { "microsoft.extensions.logging.abstractions", "1.0.0-rc1-final" },
                { "system.diagnostics.contracts", "4.0.0" },
                { "microsoft.owin.cors", "3.0.1" },
                { "system.io.unmanagedmemorystream", "4.0.0" },
                { "microsoft.extensions.logging", "1.0.0-rc1-final" },
                { "microsoft.framework.dependencyinjection.abstractions", "1.0.0-beta8" },
                { "system.security.cryptography.algorithms", "4.0.0-beta-23409" },
                { "ninject", "3.2.2" },
                { "microsoft.aspnet.signalr.systemweb", "2.2.0" },
                { "microsoft.framework.configuration", "1.0.0-beta8" },
                { "system.componentmodel.annotations", "4.0.10" },
                { "microsoft.framework.configuration.abstractions", "1.0.0-beta8" },
                { "system.security.cryptography.encoding", "4.0.0-beta-23409" },
                { "system.security.cryptography.x509certificates", "4.0.0-beta-23409" },
                { "system.xml.xdocument", "4.0.10" },
                { "microsoft.extensions.primitives", "1.0.0-rc1-final" },
                { "microsoft.framework.logging.abstractions", "1.0.0-beta8" },
                { "microsoft.extensions.configuration.abstractions", "1.0.0-rc1-final" },
                { "webactivatorex", "2.0.6" },
                { "microsoft.extensions.platformabstractions", "1.0.0-rc1-final" },
                { "microsoft.framework.dependencyinjection", "1.0.0-beta8" },
                { "microsoft.codeanalysis.analyzers", "1.0.0" },
                { "microsoft.extensions.configuration", "1.0.0-rc1-final" },
                { "nuget.build", "2.8.6" },
                { "microsoft.framework.primitives", "1.0.0-beta8" },
                { "microsoft.framework.logging", "1.0.0-beta8" },
                { "microsoft.framework.optionsmodel", "1.0.0-beta8" },
                { "xunit.runner.console", "2.1.0" },
                { "microsoft.framework.configuration.binder", "1.0.0-beta8" },
                { "microsoft.aspnet.signalr", "2.2.0" },
                { "microsoft.framework.configuration.json", "1.0.0-beta8" },
                { "system.linq.parallel", "4.0.0" },
                { "microsoft.dnx.runtime.abstractions", "1.0.0-beta8" },
                { "microsoft.framework.configuration.fileextensions", "1.0.0-beta8" },
                { "system.io.filesystem.watcher", "4.0.0-beta-23409" },
                { "microsoft.netcore.targets", "1.0.0" },
                { "microsoft.framework.webencoders.core", "1.0.0-beta8" },
                { "microsoft.aspnet.http.abstractions", "1.0.0-beta8" },
                { "microsoft.aspnet.http.features", "1.0.0-beta8" },
                { "microsoft.aspnet.fileproviders.abstractions", "1.0.0-beta8" },
                { "microsoft.aspnet.hosting.abstractions", "1.0.0-beta8" },
                { "system.componentmodel.typeconverter", "4.0.1-beta-23409" },
                { "microsoft.net.http.headers", "1.0.0-beta8" },
                { "microsoft.aspnet.http.extensions", "1.0.0-beta8" },
                { "microsoft.dnx.compilation.abstractions", "1.0.0-beta8" },
                { "system.diagnostics.tracing.telemetry", "4.0.0-beta-23409" },
                { "microsoft.aspnet.webutilities", "1.0.0-beta8" },
                { "microsoft.aspnet.fileproviders.physical", "1.0.0-beta8" },
                { "system.net.websockets", "4.0.0-beta-23409" },
                { "microsoft.extensions.dependencyinjection", "1.0.0-rc1-final" },
                { "microsoft.framework.configuration.environmentvariables", "1.0.0-beta8" },
                { "system.net.networkinformation", "4.0.0" },
                { "microsoft.aspnet.http", "1.0.0-beta8" },
                { "microsoft.framework.configuration.commandline", "1.0.0-beta8" },
                { "microsoft.aspnet.hosting", "1.0.0-beta8" },
                { "microsoft.aspnet.hosting.server.abstractions", "1.0.0-beta8" },
                { "microsoft.framework.webencoders", "1.0.0-beta8" },
                { "microsoft.netcore.platforms", "1.0.0" },
                { "microsoft.aspnet.server.kestrel", "1.0.0-beta8" },
                { "elmah.corelibrary", "1.2.2" },
                { "system.numerics.vectors", "4.1.1-beta-23409" },
                { "system.diagnostics.stacktrace", "4.0.1-beta-23409" },
                { "runtime.unix.system.diagnostics.tracesource", "4.0.0-beta-23409" },
                { "microsoft.owin.hosting", "3.0.1" },
                { "microsoft.aspnet.staticfiles", "1.0.0-beta8" },
                { "runtime.unix.system.security.cryptography.encoding", "4.0.0-beta-23409" },
                { "runtime.unix.system.security.cryptography.x509certificates", "4.0.0-beta-23409" },
                { "system.security.cryptography.openssl", "4.0.0-beta-23409" },
                { "runtime.unix.system.console", "4.0.0-beta-23409" },
                { "automapper", "4.1.1" },
                { "runtime.unix.system.private.uri", "4.0.1-beta-23409" },
                { "runtime.unix.system.threading", "4.0.11-beta-23409" },
                { "microsoft.extensions.configuration.binder", "1.0.0-rc1-final" },
                { "runtime.linux.system.runtime.extensions", "4.0.11-beta-23409" },
                { "runtime.unix.system.diagnostics.debug", "4.0.11-beta-23409" },
                { "runtime.linux.system.io.filesystem", "4.0.1-beta-23409" },
                { "system.diagnostics.diagnosticsource", "4.0.0-beta-23516" },
                { "runtime.linux.system.security.cryptography.algorithms", "4.0.0-beta-23409" },
                { "runtime.unix.system.globalization.extensions", "4.0.1-beta-23409" },
                { "runtime.unix.system.net.primitives", "4.0.11-beta-23409" },
                { "runtime.linux.system.io.filesystem.watcher", "4.0.0-beta-23409" },
                { "microsoft.extensions.optionsmodel", "1.0.0-rc1-final" },
                { "xunit.runner.visualstudio", "2.1.0" },
                { "microsoft.netcore.targets.universalwindowsplatform", "5.0.0" },
                { "system.xml.xmlserializer", "4.0.10" },
                { "microsoft.extensions.webencoders.core", "1.0.0-rc1-final" },
                { "dapper", "1.42.0" },
                { "system.runtime.interopservices.windowsruntime", "4.0.0" },
                { "system.net.webheadercollection", "4.0.0" },
                { "nunittestadapter", "2.0.0" },
                { "rx-core", "2.2.5" },
                { "dnx-coreclr-linux-x64", "1.0.0-beta8" },
                { "system.reflection.dispatchproxy", "4.0.0" },
                { "rx-interfaces", "2.2.5" },
                { "microsoft.netcore.runtime.coreclr-x64", "1.0.0" },
                { "system.text.encoding.codepages", "4.0.0" },
                { "rx-linq", "2.2.5" },
                { "microsoft.netcore.runtime.coreclr-x86", "1.0.0" },
                { "microsoft.jquery.unobtrusive.ajax", "3.2.3" },
                { "microsoft.extensions.configuration.json", "1.0.0-rc1-final" },
                { "microsoft.extensions.caching.abstractions", "1.0.0-rc1-final" },
                { "microsoft.extensions.caching.memory", "1.0.0-rc1-final" },
                { "castle.core", "3.3.3" },
                { "nuget.galleryuptime", "1.0.0" },
                { "microsoft.extensions.configuration.fileextensions", "1.0.0-rc1-final" },
                { "microsoft.visualbasic", "10.0.0" },
                { "xunit.runner.reporters", "2.1.0" },
                { "system.runtime.serialization.json", "4.0.0" },
                { "microsoft.owin.security.jwt", "3.0.1" },
                { "system.runtime.windowsruntime", "4.0.10" },
                { "system.security.cryptography.cng", "4.0.0-beta-23516" },
                { "microsoft.extensions.configuration.environmentvariables", "1.0.0-rc1-final" },
                { "ix-async", "1.2.5" },
                { "microsoft.extensions.configuration.commandline", "1.0.0-rc1-final" },
                { "microsoft.extensions.webencoders", "1.0.0-rc1-final" },
                { "microsoft.netcore.runtime.coreclr-arm", "1.0.0" },
                { "autofac.webapi2", "3.4.0" },
                { "microsoft.codeanalysis.csharp", "1.1.0-rc1-20151109-01" },
                { "system.runtime.serialization.primitives", "4.0.10" },
                { "system.threading.tasks.dataflow", "4.5.25" },
                { "microsoft.codeanalysis.common", "1.1.0-rc1-20151109-01" },
                { "bouncycastle", "1.7.0" },
                { "rx-platformservices", "2.2.5" },
                { "documentformat.openxml", "2.5.0" },
                { "microsoft.owin.host.httplistener", "3.0.1" },
                { "enterpriselibrary.transientfaulthandling", "6.0.1304" },
                { "system.io.compression.zipfile", "4.0.0" },
                { "microsoft.aspnet.html.abstractions", "1.0.0-rc1-final" },
                { "microsoft.dnx.compilation.csharp.abstractions", "1.0.0-rc1-final" },
                { "system.private.datacontractserialization", "4.0.0" },
                { "microsoft.aspnet.cryptography.internal", "1.0.0-rc1-final" },
                { "microsoft.aspnet.razor.runtime", "4.0.0-rc1-final" },
                { "microsoft.aspnet.dataprotection", "1.0.0-rc1-final" },
                { "microsoft.aspnet.dataprotection.abstractions", "1.0.0-rc1-final" },
                { "microsoft.aspnet.diagnostics.abstractions", "1.0.0-rc1-final" },
                { "microsoft.aspnet.authorization", "1.0.0-rc1-final" },
                { "microsoft.aspnet.mvc.core", "6.0.0-rc1-final" },
                { "microsoft.extensions.memorypool", "1.0.0-rc1-final" },
                { "microsoft.aspnet.mvc.abstractions", "6.0.0-rc1-final" },
                { "microsoft.aspnet.routing", "1.0.0-rc1-final" },
                { "microsoft.aspnet.iisplatformhandler", "1.0.0-rc1-final" },
                { "microsoft.aspnet.jsonpatch", "1.0.0-rc1-final" },
                { "system.runtime.serialization.xml", "4.0.10" },
                { "microsoft.extensions.localization.abstractions", "1.0.0-rc1-final" },
                { "microsoft.extensions.localization", "1.0.0-rc1-final" },
                { "microsoft.aspnet.antiforgery", "1.0.0-rc1-final" },
                { "microsoft.aspnet.pageexecutioninstrumentation.interfaces", "1.0.0-rc1-final" },
                { "microsoft.aspnet.mvc.razor.host", "6.0.0-rc1-final" },
                { "microsoft.extensions.globalization.cultureinfocache", "1.0.0-rc1-final" },
                { "microsoft.aspnet.localization", "1.0.0-rc1-final" },
                { "sendgrid.smtpapi", "1.3.1" },
                { "microsoft.aspnet.mvc.formatters.json", "6.0.0-rc1-final" },
                { "microsoft.netcore.portable.compatibility", "1.0.0" },
                { "microsoft.aspnet.mvc.viewfeatures", "6.0.0-rc1-final" },
                { "microsoft.aspnet.mvc.dataannotations", "6.0.0-rc1-final" },
                { "microsoft.aspnet.mvc.razor", "6.0.0-rc1-final" },
                { "microsoft.aspnet.mvc.apiexplorer", "6.0.0-rc1-final" },
                { "microsoft.aspnet.mvc.cors", "6.0.0-rc1-final" },
                { "rx-main", "2.2.5" },
                { "microsoft.aspnet.mvc.localization", "6.0.0-rc1-final" },
                { "microsoft.aspnet.razor.runtime.precompilation", "4.0.0-rc1-final" },
                { "microsoft.netcore.runtime", "1.0.0" },
                { "microsoft.dnx.compilation.csharp.common", "1.0.0-rc1-final" }
            };
        }

        /// <summary>
        /// get a version for a certain package name
        /// </summary>
        /// <param name="name">Package name.</param>
        /// <returns>returns a string with package version, if package name is present in a map,
        /// null otherwise</returns>
        public string GetVersion(string name)
        {
            if (versions.ContainsKey(name))
            {
                return versions[name];
            }
            else
            {
                return null;
            }
        }
    }
}

